-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 21:53:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fowler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fowler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fowler` DEFAULT CHARACTER SET utf8 ;
USE `fowler` ;

-- -----------------------------------------------------
-- Table `fowler`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fowler`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `gender` INT NULL,
  `birthdate` VARCHAR(45) NULL,
  `studentnr` INT NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fowler`.`Observation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fowler`.`Observation` (
  `idObservation` INT NOT NULL AUTO_INCREMENT,
  `Person_idPerson` INT NOT NULL,
  PRIMARY KEY (`idObservation`),
  INDEX `fk_Observation_Person_idx` (`Person_idPerson` ASC),
  CONSTRAINT `fk_Observation_Person`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `fowler`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fowler`.`Phenomenon_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fowler`.`Phenomenon_Type` (
  `idPhenomenon_Type` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idPhenomenon_Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fowler`.`Quantity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fowler`.`Quantity` (
  `idQuanitity` INT NOT NULL AUTO_INCREMENT,
  `value` INT NULL,
  `unit` VARCHAR(45) NULL,
  PRIMARY KEY (`idQuanitity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fowler`.`Measurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fowler`.`Measurement` (
  `idMeasurement` INT NOT NULL AUTO_INCREMENT,
  `Observation_idObservation` INT NOT NULL,
  `Phenomenon_Type_idPhenomenon_Type` INT NOT NULL,
  `Quantity_idQuanitity` INT NOT NULL,
  `timestamp` DATETIME NULL,
  PRIMARY KEY (`idMeasurement`),
  INDEX `fk_Measurement_Observation1_idx` (`Observation_idObservation` ASC),
  INDEX `fk_Measurement_Phenomenon_Type1_idx` (`Phenomenon_Type_idPhenomenon_Type` ASC),
  INDEX `fk_Measurement_Quantity1_idx` (`Quantity_idQuanitity` ASC),
  CONSTRAINT `fk_Measurement_Observation1`
    FOREIGN KEY (`Observation_idObservation`)
    REFERENCES `fowler`.`Observation` (`idObservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Measurement_Phenomenon_Type1`
    FOREIGN KEY (`Phenomenon_Type_idPhenomenon_Type`)
    REFERENCES `fowler`.`Phenomenon_Type` (`idPhenomenon_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Measurement_Quantity1`
    FOREIGN KEY (`Quantity_idQuanitity`)
    REFERENCES `fowler`.`Quantity` (`idQuanitity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fowler`.`Phenomenon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fowler`.`Phenomenon` (
  `idPhenomenon` INT NOT NULL AUTO_INCREMENT,
  `Phenomenon_Type_idPhenomenon_Type` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idPhenomenon`),
  INDEX `fk_Phenomenon_Phenomenon_Type1_idx` (`Phenomenon_Type_idPhenomenon_Type` ASC),
  CONSTRAINT `fk_Phenomenon_Phenomenon_Type1`
    FOREIGN KEY (`Phenomenon_Type_idPhenomenon_Type`)
    REFERENCES `fowler`.`Phenomenon_Type` (`idPhenomenon_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fowler`.`Category_Observation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fowler`.`Category_Observation` (
  `idCategory_Observation` INT NOT NULL AUTO_INCREMENT,
  `Observation_idObservation` INT NOT NULL,
  `Phenomenon_idPhenomenon` INT NOT NULL,
  PRIMARY KEY (`idCategory_Observation`),
  INDEX `fk_Category_Observation_Observation1_idx` (`Observation_idObservation` ASC),
  INDEX `fk_Category_Observation_Phenomenon1_idx` (`Phenomenon_idPhenomenon` ASC),
  CONSTRAINT `fk_Category_Observation_Observation1`
    FOREIGN KEY (`Observation_idObservation`)
    REFERENCES `fowler`.`Observation` (`idObservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Category_Observation_Phenomenon1`
    FOREIGN KEY (`Phenomenon_idPhenomenon`)
    REFERENCES `fowler`.`Phenomenon` (`idPhenomenon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
