-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 20:48:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema snowflake
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema snowflake
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `snowflake` DEFAULT CHARACTER SET utf8 ;
USE `snowflake` ;

-- -----------------------------------------------------
-- Table `snowflake`.`Birthdate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `snowflake`.`Birthdate` (
  `idBirthdate` INT NOT NULL AUTO_INCREMENT,
  `day` VARCHAR(45) NULL,
  `month` VARCHAR(45) NULL,
  `year` VARCHAR(45) NULL,
  PRIMARY KEY (`idBirthdate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snowflake`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `snowflake`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `gender` INT NULL COMMENT '	',
  `studentnr` INT NULL,
  `Birthdate_idBirthdate` INT NOT NULL,
  PRIMARY KEY (`idPerson`),
  INDEX `fk_Person_Birthdate1_idx` (`Birthdate_idBirthdate` ASC),
  CONSTRAINT `fk_Person_Birthdate1`
    FOREIGN KEY (`Birthdate_idBirthdate`)
    REFERENCES `snowflake`.`Birthdate` (`idBirthdate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snowflake`.`Measurement_Facts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `snowflake`.`Measurement_Facts` (
  `idMeasurements_Facts` INT NOT NULL AUTO_INCREMENT,
  `Person_idPerson` INT NOT NULL,
  `timestamp` DATETIME NULL,
  `value` VARCHAR(45) NULL,
  `phenomenon` VARCHAR(45) NULL,
  `phenomenon_type` VARCHAR(45) NULL,
  `unit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMeasurements_Facts`),
  INDEX `fk_Measurements_Facts_Person1_idx` (`Person_idPerson` ASC),
  CONSTRAINT `fk_Measurements_Facts_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `snowflake`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
