-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 19:50:46 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema starschema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema starschema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `starschema` DEFAULT CHARACTER SET utf8 ;
USE `starschema` ;

-- -----------------------------------------------------
-- Table `starschema`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starschema`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `gender` INT NULL,
  `birthdate` VARCHAR(45) NULL,
  `studentnr` INT NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starschema`.`Measurement_Facts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starschema`.`Measurement_Facts` (
  `idmeasurement_facts` INT NOT NULL AUTO_INCREMENT,
  `Person_idPerson` INT NOT NULL,
  `value` VARCHAR(45) NULL,
  `timestamp` DATETIME NULL,
  `phenomenon` VARCHAR(45) NULL,
  `phenomenon_type` VARCHAR(45) NULL,
  `unit` VARCHAR(45) NULL,
  PRIMARY KEY (`idmeasurement_facts`),
  INDEX `fk_Measurement_Facts_Person1_idx` (`Person_idPerson` ASC),
  CONSTRAINT `fk_Measurement_Facts_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `starschema`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
