-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 17:12:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema starschema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema starschema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `starschema` DEFAULT CHARACTER SET utf8 ;
USE `starschema` ;

-- -----------------------------------------------------
-- Table `starschema`.`Phenomenon_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starschema`.`Phenomenon_type` (
  `idPhenomenon` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idPhenomenon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starschema`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starschema`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `gender` INT NULL,
  `birthdate` VARCHAR(45) NULL,
  `studentnr` VARCHAR(45) NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starschema`.`Unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starschema`.`Unit` (
  `idUnit` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idUnit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starschema`.`Phenomenon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starschema`.`Phenomenon` (
  `idPhenomenon` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idPhenomenon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starschema`.`Measurement_Facts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starschema`.`Measurement_Facts` (
  `idmeasurement_facts` INT NOT NULL AUTO_INCREMENT,
  `Phenomenon_idPhenomenon` INT NOT NULL,
  `Person_idPerson` INT NOT NULL,
  `Unit_idUnit` INT NOT NULL,
  `Phenomenon_idPhenomenon1` INT NOT NULL,
  `value` VARCHAR(45) NULL,
  `timestamp` DATETIME NULL,
  PRIMARY KEY (`idmeasurement_facts`),
  INDEX `fk_Measurement_Facts_Phenomenon1_idx` (`Phenomenon_idPhenomenon` ASC),
  INDEX `fk_Measurement_Facts_Person1_idx` (`Person_idPerson` ASC),
  INDEX `fk_Measurement_Facts_Unit1_idx` (`Unit_idUnit` ASC),
  INDEX `fk_Measurement_Facts_Phenomenon2_idx` (`Phenomenon_idPhenomenon1` ASC),
  CONSTRAINT `fk_Measurement_Facts_Phenomenon1`
    FOREIGN KEY (`Phenomenon_idPhenomenon`)
    REFERENCES `starschema`.`Phenomenon_type` (`idPhenomenon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Measurement_Facts_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `starschema`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Measurement_Facts_Unit1`
    FOREIGN KEY (`Unit_idUnit`)
    REFERENCES `starschema`.`Unit` (`idUnit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Measurement_Facts_Phenomenon2`
    FOREIGN KEY (`Phenomenon_idPhenomenon1`)
    REFERENCES `starschema`.`Phenomenon` (`idPhenomenon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
